name: 'Reestablish stage branch'
on:
  push: 
    branches:
      - prod

jobs:
  recreate:
    name: Recreate stage branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Recreate
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "stage"
          sha: '${{ github.event.push.head.sha }}'