name: Close production Pull Request

on:
  pull_request_target:
    types: [opened]
  branches:
    - prod

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Production branch can only be accessed through releases"